platform :ios,'8.0'
target 'note_ios_app' do
pod 'Masonry'
pod 'MJExtension'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'AFNetworking'
pod 'IQKeyboardManager'
pod 'JSQMessagesViewController'
pod 'CocoaAsyncSocket'
pod 'MBProgressHUD'
end
